
version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp
    container_name: myapp
    ports:
      - 8000:8000

    # Add additional configuration options here if needed
